name: Update News Every 2 Minutes

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run update script
        run: python update_news.py
